uninstall-user com.onyx.igetshop
uninstall-user com.onyx.aiassistant
uninstall-user com.onyx.appmarket
uninstall-user com.onyx.android.production.test
uninstall-user org.chromium.chrome
disable-user com.onyx.android.ksync
