uninstall-user com.onyx.igetshop
uninstall-user com.onyx.aiassistant
uninstall-user com.onyx.appmarket
uninstall-user com.onyx.android.production.test
uninstall-user org.chromium.chrome
disable-user com.onyx.android.ksync
uninstall-user com.onyx.easytransfer
uninstall-user com.onyx.mail
uninstall-user com.onyx.voicerecorder
uninstall-user com.onyx.musicplayer
uninstall-user com.onyx.gallery
uninstall-user com.onyx.calculator
uninstall-user com.onyx.clock
uninstall-user com.onyx.dict
